### PR TITLE
Support for sf 2.7|2.8

### PR DESCRIPTION
**Pull request by partikus**

### CODE REVIEW

**Comment by partikus** [comment]
@kubawerlos @kwojtas-pgs ping, code review please
Builds matrix can be found here: https://travis-ci.org/PGSSoft/PgsRestfonyBundle/builds/151632139

**Comment by partikus** [comment]
@kubawerlos @kwojtas-pgs @kwojtas6 @dominikhajduk @tarnawski 
code review please

**Comment by dominikhajduk** [comment]
👍 Look good for me

**Comment by tarnawski** [comment]
:+1:  approved

**Pull request merged**
